# Generated by Django 4.2.8 on 2024-05-22 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_saving_savingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='joinSaving',
            field=models.ManyToManyField(related_name='joinS', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timedeposit',
            name='joinDeposit',
            field=models.ManyToManyField(related_name='joinD', to=settings.AUTH_USER_MODEL),
        ),
    ]
