# Generated by Django 4.2.8 on 2024-05-23 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_saving_joinsaving_timedeposit_joindeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcompany',
            name='like_users',
            field=models.ManyToManyField(related_name='like_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
