# Generated by Django 4.2.8 on 2024-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
